### ISSUE TITLE
Bar graph doesn't show ordinal values on primary axis

### ISSUE THREAD

**Issue by mrlinux1** [tannerlinsley/react-charts#104]
Hello, 
I try to create a stacked bar graph like in the example.
I remapped the data so that it has the same layout as in the example bar chart:
![data_comparison](https://user-images.githubusercontent.com/9421663/88361763-660c2e80-cd7a-11ea-801c-a64344cd53d1.png)
But my graph doesn't show the names on the left side of the graph:
![graph_comparison](https://user-images.githubusercontent.com/9421663/88361777-73c1b400-cd7a-11ea-8a53-910243a2f159.png)

I use the same code snippets for my graph like in the example bar chart (data, series, axes).

Can anyone help me on that?
Kind regards,
Thomas

**Comment by mrlinux1** [comment]
Now I moved the example graph to my component and use the same series and axes memo:

 ```
     const axes = React.useMemo(
        () => [
          { primary: true, type: 'ordinal', position: 'left', primaryAxisShow: true },
          { type: 'linear', position: 'bottom', stacked: true, secondaryAxisShow: true},
        ],
        []
      )
      const series = React.useCallback(
        () => ({
          
          type: 'bar'
        }),
        []
      )
```
But I get the same result.
But the data looks the same:
![react](https://user-images.githubusercontent.com/9421663/88622025-21e29c00-d0a2-11ea-8aef-c16788fe6213.png)

I'm really frustrated as I need that until next weekend.

Kind regards,

Thomas

**Comment by evenstephenr** [comment]
@mrlinux1 I took a look at the react-charts internal API and it doesn't look like ordinal groups let you customize the axis label ☹️ 

To clarify for my own understanding, are you looking to replace the 'ordinal group' label with a categorical group label - in your case, country name?
