### ISSUE TITLE
Do series need to forcefully be separated as distinct elements in the source data array?

### ISSUE THREAD

**Issue by HectorRicardo** [tannerlinsley/react-charts#105]
How can I plot these data points in a line graph?

```javascript
const originalData = [
  { x: 0, series1: 0, series2: 0, series3: 0 },
  { x: 1, series1: 1, series2: 2, series3: 3 },
  { x: 2, series1: 2, series2: 4, series3: 6 },
  { x: 3, series1: 3, series2: 6, series3: 9 },
];
```

Expected output:

![image](https://user-images.githubusercontent.com/16261233/88737383-977c5580-d0fe-11ea-9d1a-cd6c79f187f8.png)

I checked the Data Model docs at [https://react-charts.tanstack.com/docs/api#data-model](https://react-charts.tanstack.com/docs/api#data-model) and the `data` of the examples have the series' values separated in different arrays:

```javascript
[
  {
    label: 'Series 1', // series 1
    data: [
      { x: 1, y: 10 },
      { x: 2, y: 10 },
      { x: 3, y: 10 },
    ],
  },
  {
    label: 'Series 2', // series 2
    data: [
      { x: 1, y: 10 },
      { x: 2, y: 10 },
      { x: 3, y: 10 },
    ],
  },
  ... // more series, but each as a separate element of the array
]
```

However, in my example, each series value is intertwined with other series' values:
```javascript
const originalData = [
  { x: 0, series1: 0, series2: 0, series3: 0 }, // series 1, 2, and 3 in the same datum
  ...
];
```

Is it possible to graph this format of data directly without having to do a transformation of my original data array?

**Comment by evenstephenr** [comment]
@HectorRicardo I took a look at the react-charts internal lib, and it looks like this middleware is being called on every instance of a base Chart component

https://github.com/tannerlinsley/react-charts/blob/next/src/components/pipeline/useMaterializeData.js#L9

In the code here, it seems like the model you referenced is accurate 👍

**Comment by tannerlinsley** [comment]
You will need to transform the data into [this structure](https://react-charts.tanstack.com/docs/api#data-model)
