### ISSUE TITLE
Overwrite the tooltip label

### ISSUE THREAD

**Issue by darthzeran** [tannerlinsley/react-charts#107]
Is there a way to change the label for the tooltip?
For example, my x axis is dates (Specifically, Date objects),
and I would like to overwrite how the tooltip shows my data points.  All it is doing is grabbing the getTime() of the date object, so the tooltip shows my data labelled as `561`, `334`, etc, representing the milliseconds of my Date object.

In the docs, I cannot find a way of changing that without creating a brand new tooltip. Any suggestions?

**Comment by evenstephenr** [comment]
@darthzeran Here's a codesandbox showing how to override the default Tooltips with a custom component. 

https://codesandbox.io/s/github/tannerlinsley/react-charts/tree/next/examples/custom-tooltip

Does this help?
