### ISSUE TITLE
TypeError: curve is not a function

### ISSUE THREAD

**Issue by andrewgarrison** [tannerlinsley/react-charts#117]
The [WIP API docs](https://react-charts.tanstack.com/docs/api#curve-types) state that you can pass a `curve` prop to a series component in order to form a continuous shape between points. There's even a short code example showing this:

```
function MyChart() {
   const series = React.useMemo(() => ({ curve: 'cardinal' }), [])
 
   return <Chart series={series} />
}
```

However, when adding the curve prop with one of the listed curve types, the following error occurs:

```
TypeError: curve is not a function
line /node_modules/react-charts/dist/react-charts.mjs:4424:34


  4421 | var x$1 = x, y$1 = y, defined = constant$2(true), context = null, curve = curveLinear, output = null;
  4422 | function line(data) {
  4423 |   var i, n = data.length, d, defined0 = false, buffer;
> 4424 |   if (context == null) output = curve(buffer = path());
       |                                ^
  4425 |   for (i = 0; i <= n; ++i) {
  4426 |     if (!(i < n && defined(d = data[i], i, data)) === defined0) {
  4427 |       if (defined0 = !defined0) output.lineStart(); else output.lineEnd();
```
Here's a sandbox showing this:
https://codesandbox.io/s/vigilant-forest-lrex3?file=/src/index.js

I'm on `react-charts ^2.0.2-next.15` and `react ^16.13.1`. I also tried installing the `d3-shape` package and using a curve function from there but that did not seem to work either.

**Comment by tannerlinsley** [comment]
Try importing curveCardinal from React Charts and passing that.

Tanner Linsley

**Comment by andrewgarrison** [comment]
Ah, that worked in the Sandbox. Not initially in my local project but it was due to an issue with the data on my end. Thanks!
