### ISSUE TITLE
Y Axis real numbers to integer value

### ISSUE THREAD

**Issue by silpa4** [tannerlinsley/react-charts#123]
In the Y-axis, it gives me real numbers(decimal value) instead of integers. How can I change the number to integers?

**Comment by darthzeran** [comment]
Same, except I am making my x axis time like so 
```
{
	primary: true,
	type: 'time',
	position: 'bottom',
},
```
,
but If i only have one value, it show the milliseconds of the Date timestamp I pass in, how can i make it show the date, instead of just the milliseconds?

**Comment by darthzeran** [comment]
Same, except I want to make my time oriented x axis show an actual Date if there is 1 data point, rather than the milliseconds of the timestamp.  Is there a way to edit the value of the axis?

**Comment by RobertMcReed** [comment]
I believe there are a couple ways you can do this. How I achieve this is by passing a formatting function when defining my axes. Mine is shared below. Notice how for the primary axis I'm mapping the value into some `tspan` elements for greater control over the formatting, but in the secondary axis I am simply returning a string. In both cases, the value that is passed into the function is the value for that datum, ie `datum.x` or `datum.y`.

```
const axes = useMemo(
    () => [
      {
        primary: true,
        type: 'ordinal',
        position: 'bottom',
        format: (identifier) => (
          <tspan>
            {identifier.split(splitKey).map((part, i) => (
              <tspan x="0%" y="-10px" dy={`${i * 12}px`} key={identifier + part}>
                {part}
              </tspan>
            ))}
          </tspan>
        ),
      },
      {
        position: 'left',
        type: 'linear',
        stacked: false,
        id: 'default',
        hardMin: 0,
        format: (num) => (units ? `${num} ${units}` : num),
      },
    ],
    [units],
  );
```

You can also pass functions `getPrimary` and `getSecondary`, but I find setting the formatter in the axes more useable.

**Comment by Danjosh0211** [comment]
I had the same issue and managed to solve it using the format too. It appeared using a linear axes, the numbers were always decimals when the axis had less than 10 values on it and it didn't make any sense for the context of the graph. 
I wasn't sure if the ticks were working however i managed to force it to be integers by using the format function as such:


```      
  const axes = React.useMemo(
    () => [
      { primary: true, position: 'bottom', type: 'linear', format: (d) => {
        console.log(d);
        d = parseFloat(d);
        //only show integer numbers
        if (d % 1 == 0) {
          return `${d.toFixed(0)}`;
        }
        return ``;
      },},
      { position: 'left', type: 'linear', stacked: false,  hardMin:0, hardMax:9  }
    ],
    []
  )
```

**Comment by tannerlinsley** [comment]
Due to a massive overhaul and rewrite of React Charts to TypeScript and a massively upgraded public API, this issue is being bulk closed for triage. The latest version can be tested via the `react-charts@beta` tag. Documentation is in the process of being upgraded, but thankfully, everything is fully typed now, so you can explore the API that way for now.

If, *after testing or playing with the v3 beta*, you believe your issue is still not addressed or relevant, feel free to open a new issue.
