### ISSUE TITLE
Error when trying to display a line chart

### ISSUE THREAD

**Issue by TravelingTechGuy** [tannerlinsley/react-charts#131]
I get the same error consistently when trying to draw a line chart:

```
react-dom.production.min.js:28 Error: <path> attribute d: Expected number, "M0,NaNZM0,NaNL0,NaN…".
G @ react-dom.production.min.js:28
react-dom.production.min.js:28 Error: <path> attribute d: Expected number, "…428617724867724,NaNZM-19.4286177…".
G @ react-dom.production.min.js:28
react-dom.production.min.js:28 Error: <path> attribute d: Expected number, "…8.2936433883142,NaNZM618.2936433…".
G @ react-dom.production.min.js:28
react-dom.production.min.js:28 Error: <path> attribute d: Expected number, "….64922263730773,NaNZM413.6492226…".
G @ react-dom.production.min.js:28
```

The series has 136 points, with values primary values being dates, and secondary values number ranging from 0 to 100,000,000. I've verified all the items are indeed valid dates and numbers.

The result is see is a bunch of dots at the top of the chart, and a stream of errors like the ones mentioned above.

I can share the data if needed. I managed to reproduce it with a single chart just showing this set.

Is there a limit to number of points/range of dates/range of values that I missed in the documentation?

Thanks for your time!

**Comment by NillerMedDild** [comment]
I had the same issue as you, I resolved it by changing all occurrences of the `secondary` value `0` to `0.1`

**Comment by TravelingTechGuy** [comment]
> I had the same issue as you, I resolved it by changing secondary values that were `0` to `0.1`

But that creates incorrect data and "noise". As a workaround, maybe a much smaller value (0.0001?) would work, but I still hope this get fixed.

**Comment by NillerMedDild** [comment]
Yep, smaller values also work :)

**Comment by kumarpatel** [comment]
Below workaround seems a little better than modifying values.
https://github.com/tannerlinsley/react-charts/issues/126#issuecomment-712844329

**Comment by tannerlinsley** [comment]
Due to a massive overhaul and rewrite of React Charts to TypeScript and a massively upgraded public API, this issue is being bulk closed for triage. The latest version can be tested via the `react-charts@beta` tag. Documentation is in the process of being upgraded, but thankfully, everything is fully typed now, so you can explore the API that way for now.

If, *after testing or playing with the v3 beta*, you believe your issue is still not addressed or relevant, feel free to open a new issue.
