### ISSUE TITLE
Can't resolve 'performance-now'

### ISSUE THREAD

**Issue by alex-r89** [tannerlinsley/react-charts#133]
Hi there,

I ran into the following error:

```./node_modules/react-charts/dist/react-charts.development.js
Module not found: Can't resolve 'performance-now' in 'my-folder/node_modules/react-charts/dist'
```

I am using the exact code example from the npm page under "Quick Start". 

To also note, I am using NextJS, although I don't think that matters

This is on `react-charts` `2.0.0-beta.7`

**Comment by tfsjohan** [comment]
Same here. Also using Next.

**Comment by quinceleaf** [comment]
Same here! Also using Next

**Comment by tfsjohan** [comment]
I added the performance-now package manually to my package.json. That works. But as a more annoying point it does not work at all when running a production build of the package in Next. 

Tried to load it with nexts dynamic import and avoid ssr, but then I get absolutely nothing at all.

**Comment by creativeBernadka** [comment]
Same here. I am using Next `10.0.2` and tried versions of react-charts `2.0.0-beta.7`, `2.0.0 `and `1.0.9`

**Comment by francofantini** [comment]
Any news on this issue?

**Comment by klawdyo** [comment]
Same here. Also using Next.

**Comment by jasuno** [comment]
same here

**Comment by lvilasboas** [comment]
same here

**Comment by khanz1** [comment]
same here

**Comment by embeddedt** [comment]
The demo on https://react-charts.tanstack.com/examples/bar is also having this issue.

**Comment by tannerlinsley** [comment]
The latest beta should not exhibit this issue any more.
