### ISSUE TITLE
Axes labels not shown

### ISSUE THREAD

**Issue by tfsjohan** [tannerlinsley/react-charts#134]
I've created a really simple example but labels on the axes are not shown. I see correct labels while hovering the a data point and lines are correct. 

```
    const dataMemo = React.useMemo(
        () => [
            {
                label: label,
                data: data.map(item => ({primary: item.x, secondary: item.y}))
            }
        ],
        [data]
    );

    const axes = React.useMemo(
        () => [
            {primary: true, type: 'ordinal', position: 'bottom'},
            {type: 'linear', position: 'left'}
        ],
        []
    );

    const series = React.useMemo(
        () => ({
            type: 'line'
        }),
        []
    );
```

```
    <div className={'chartbox'}>
                        <Chart data={dataMemo} series={series} axes={axes} tooltip/>
                    </div>
```

**Comment by christiankaindl** [comment]
@tfsjohan do the axes show up if you resize the browser window?

I face a similar issue, but it only occurs on first render of the chart. E.g. when I resize the window it redraws the charts and looks correct (with the labels). Although I haven't found a workaround/fix yet.

**Comment by aidinism** [comment]
> @tfsjohan do the axes show up for you when you resize the browser window?
> 
> I face a similar issue, but it only occurs on the first render of the chart. E.g. when I resize the window it redraws the charts and looks correct (with the labels). Although I haven't found a workaround/fix yet.

I face the same issue.

the first render:
![image](https://user-images.githubusercontent.com/141910/102437183-f9b2f580-3fce-11eb-8a5d-13b7920d1fef.png)


any other:
![image](https://user-images.githubusercontent.com/141910/102437246-1818f100-3fcf-11eb-9101-33fc0e8bfa49.png)

**Comment by AbdallahMezo** [comment]
After investigation, I found that the issue happens when data passed to the chart was empty and then updated. 

```
console.log(chartData)
// []
// [{...}, {...}, {...}]
```

the solution I implemented is to not render the chart until data is fetched.

**Comment by tannerlinsley** [comment]
This should be fixed in the latest beta
