### ISSUE TITLE
Animated Example removed

### ISSUE THREAD

**Issue by webdesign2be** [tannerlinsley/react-charts#136]
Hi,

Unfortunately the "animated" example (https://react-charts.tanstack.com/examples/animated)
is removed from the repository.
The codesandbox is also "dead" (https://codesandbox.io/s/github/tannerlinsley/react-charts/tree/next/examples/animated)

Kind regards

**Comment by tannerlinsley** [comment]
The next beta is a huge overhaul and even more example are in flux.
