### ISSUE TITLE
Tooltips don't show decimal values.

### ISSUE THREAD

**Issue by lucasblackhurst** [tannerlinsley/react-charts#141]
I have a line chart that is not showing decimal values within the tooltips.

![image](https://user-images.githubusercontent.com/14875084/101634123-28a1f800-3a20-11eb-86ae-6af1f60bfd0e.png)

My data;
color: "#E12827"
data: Array(10)
0: (2) [0, 0]
1: (2) [1, 4.4]
2: (2) [2, 4.4]
3: (2) [3, 4.4]
4: (2) [4, 4.4]
5: (2) [5, 4.4]
6: (2) [6, 4.4]
7: (2) [7, 4.4]
8: (2) [8, 4.4]
9: (2) [9, 8.4]
label: "Absence"

My axis are set to;
{
                position: 'left',
                type: 'linear',
                show: false,
                hardMin: -1,
                hardMax: max + 1,
                format: d => `${d} accumulated hours`
            }

Any ideas what is causing this? Is there something I need to enable?

TIA

**Comment by mortimr** [comment]
Having the same issue, unable to display any decimal value !

**Comment by jonasberglund** [comment]
I solved it like this
```
  const tooltip = React.useMemo(
    () => ({
      formatSecondary: (d) => d.toFixed(1),
    }),
    [],
  );

  <Chart data={data} axes={axes} tooltip={tooltip} />
```

**Comment by lucasblackhurst** [comment]
Thanks! That has worked for the axes value but the series total doesn't seem to be affected.

**Comment by tannerlinsley** [comment]
Due to a massive overhaul and rewrite of React Charts to TypeScript and a massively upgraded public API, this issue is being bulk closed for triage. The latest version can be tested via the `react-charts@beta` tag. Documentation is in the process of being upgraded, but thankfully, everything is fully typed now, so you can explore the API that way for now.

If, *after testing or playing with the v3 beta*, you believe your issue is still not addressed or relevant, feel free to open a new issue.

**Comment by graylewis** [comment]
For anyone that stumbles across this, you can now use the `formatters` object on the relevant AxisOptions you define to handle this, e.g.:
```
const secondaryAxes = React.useMemo(
    (): AxisOptions<TerpeneData>[] => [
      {
        getValue: datum => datum.value,
        elementType: 'bar',
        min: 0,
        max: 1,
        styles: {
          tick: {
            fill: 'white',
            fontSize: '64px !important',
          },
          fontSize: '64px !important',
        },
        formatters: {
          tooltip: datum => datum.toFixed(3),
        }
      },
    ],
    [],
  )
```

Here, I use the formatters.tooltip function to specify how the value should be formatted. Best of luck!
