### ISSUE TITLE
Excessive svg path precision

### ISSUE THREAD

**Issue by baryluk** [tannerlinsley/react-charts#169]
I was testing

https://codesandbox.io/s/github/tannerlinsley/react-charts/tree/next/examples/stress-test?file=/src/index.js

with big number of data points (1 chart, 1 series, 20000 points)

One of the issues I noticed (in Firefox 78.9.0esr (64-bit), on Linux amd64), is excessive precision, leading to a bloat:

```svg
<path d="M448.46999999999997,0.6300000000000006C431.85999999999996,2.9399999999999995,415.25,5.25,398.64,7.56C369.95,11.55,341.26,15.540000000000003,312.57,19.530000000000005C228.01,31.290000000000013,143.45,43.05000000000001,58.89,54.81C43.79,56.910000000000004,28.689999999999998,61.11,13.59,61.11C28.689999999999998,61.11,43.79,56.910000000000004,58.89,54.81C175.16,38.640000000000015,291.43,22.470000000000013,407.7,6.299999999999999C277.84000000000003,24.360000000000007,147.98,42.42,18.12,60.48C58.89,54.809999999999995,99.66,49.14,140.43,43.47C202.34,34.86,264.25,26.249999999999982,326.15999999999997,17.64C258.21,27.089999999999982,190.26,36.54,122.31,45.99C218.95,32.54999999999999,315.59000000000003,19.11,412.23,5.669999999999998C357.87,13.229999999999997,303.51000000000005,20.79,249.15000000000003,28.349999999999998C187.24000000000004,36.96,125.33000000000001,45.57,63.42000000000001,54.18C170.63,39.27,277.84000000000003,24.36,385.05,9.450000000000001C401.66,7.1400000000000015,418.27,4.830000000000002,434.88,2.5200000000000022C338.24,15.96,241.6,29.4,144.96,42.839999999999996C206.87,34.23,268.78,25.62,330.69,17.01C320.12,18.48,309.55,19.95,298.98,21.419999999999998C333.71000000000004,16.59,368.44,11.759999999999998,403.17,6.929999999999999C353.34000000000003,13.859999999999996,303.51000000000005,20.789999999999992,253.68000000000004,27.719999999999995C261.23,26.669999999999998,268.78,25.619999999999997,276.33,24.57C209.89,33.81000000000001,143.45,43.050000000000004,77.01,52.29C55.870000000000005,55.23,34.730000000000004,....
```

This persists in memory, and consumes about 30MB as strings. If not more.

While, it is true, that for example first value, `448.46999999999997`, is not the same as `448.47`, and both are minimal representations, from practical point of view, there is almost no difference. Considering the path is going to be plotted on less than 4000x2000 canvas (usually way less), having more than 5 significant decimal digits for most of coordinates is a total overkill.

**Comment by tannerlinsley** [comment]
We use d3 for path generation. So this is likely upstream.

Tanner Linsley

**Comment by tannerlinsley** [comment]
Due to a massive overhaul and rewrite of React Charts to TypeScript and a massively upgraded public API, this issue is being bulk closed for triage. The latest version can be tested via the `react-charts@beta` tag. Documentation is in the process of being upgraded, but thankfully, everything is fully typed now, so you can explore the API that way for now.

If, *after testing or playing with the v3 beta*, you believe your issue is still not addressed or relevant, feel free to open a new issue.
