### ISSUE TITLE
Missing Dependeny on Sandboxes: perfomance-now

### ISSUE THREAD

**Issue by guamacherox** [tannerlinsley/react-charts#174]
The sandboxes available on https://react-charts.tanstack.com/ have a missing dependency -> **perfomance-now**

![image](https://user-images.githubusercontent.com/4821132/117004169-289ae100-acbc-11eb-845f-36772390d297.png)

You can install it manually but that will be a fork of the provided sandboxes

**Comment by davwheat** [comment]
This is also the case locally. Can we get this fixed?
