### ISSUE TITLE
Sandbox examples are all broken in the documentation

### ISSUE THREAD

**Issue by vidup** [tannerlinsley/react-charts#212]
Hello,

As I said in the title, the code sandboxes used in the documentation seem to be broken.
I get this error for every single one I tried: 
![image](https://user-images.githubusercontent.com/6061078/125056843-eff6f980-e0a8-11eb-8193-26ab3e7023c0.png)

It looks like the sandboxes themselves do not exist / are not accessible anymore, since this happens when I try to access them directly on https://codesandbox.io/
![image](https://user-images.githubusercontent.com/6061078/125057016-15840300-e0a9-11eb-9aca-db2cd766060e.png)

**Comment by tannerlinsley** [comment]
We are currently working on bringing back the code sandboxes for the new V3 beta version. Stay tuned.
