### ISSUE TITLE
No examples showing

### ISSUE THREAD

**Issue by PrateekGoyal18** [tannerlinsley/react-charts#223]
All the previous [examples](https://react-charts.tanstack.com/examples/simple) at this link are not showing now, and the one which is available is not being complied correctly by CodeSandbox.

![image](https://user-images.githubusercontent.com/15648366/126036345-da52554b-5065-4a1b-ad10-287b5e6631d9.png)

**Comment by tannerlinsley** [comment]
Just needed an npm upgrade. It’s working now :)

**Comment by PrateekGoyal18** [comment]
The example for simple chart is running, but can't see other types of charts in the example tab.
![image](https://user-images.githubusercontent.com/15648366/126899162-f9da1169-2499-4f0d-a368-617a74d56915.png)

**Comment by tannerlinsley** [comment]
The simple example contains all of the chart types in one sandbox.
