### ISSUE TITLE
Error order in line chart

### ISSUE THREAD

**Issue by nemozar** [tannerlinsley/react-charts#229]
In datasourse 4 line where primary with a pass date. In a dataset, dates are in order, but with a pass date.
![image](https://user-images.githubusercontent.com/4721820/127459139-f1d3702f-4b76-4687-9deb-b30390c86c77.png)

after rendering some line has error primary order date

![image](https://user-images.githubusercontent.com/4721820/127459355-c96b02e2-5a5d-4ef0-a5c0-c491ee696a35.png)

Data before build datasourse has not a complete set for all primary and lines

![image](https://user-images.githubusercontent.com/4721820/127459544-baf732dd-2ef8-4bbc-a2ee-6fa1719fc877.png)

**Comment by tannerlinsley** [comment]
You need to make a CodeSandBox for this otherwise I can’t debug it.
