### ISSUE TITLE
Chart x axis has empty space.

### ISSUE THREAD

**Issue by artbelikov** [tannerlinsley/react-charts#255]
<img width="798" alt="Screen Shot 2021-10-21 at 13 13 06" src="https://user-images.githubusercontent.com/9851825/138251622-fba1676f-5103-4551-a50d-4a6bbf47c29f.png">

Hi! I am struggling with this situation. As seen on image the chart window is wider than the line. I wish there was no empty space at the start and the end. I checked first and last points values and they are correct. Tried to tinker with options hardMax and hardMin - no luck. Any advice?

**Comment by kreftk** [comment]
Set the `shouldNice` option to `false`.

**Comment by artbelikov** [comment]
many thanks!
