### ISSUE TITLE
Custom ticks

### ISSUE THREAD

**Issue by NissanAloni** [tannerlinsley/react-charts#30]
Hi,

I'm trying create a Bar chart with custom X axis ticks.

Here's a snippet:
								<Chart
										  type="bar"
										  data={[
											{
											  label: "MyData",
											  data: [[0, 5],[1,7],[2,3]] 
											}
										  ]} 
											axes={[
											  { primary: true, type: "ordinal", position: "bottom", showGrid: true ,tickValues: ["a,","b","c"]},
											  {  type: "linear", position: "left", showGrid: true ,hardMin:-1,hardMax:10}
											]}
										  />

However, this causes the X-axis ticks to be written over each other.
All the x-axis text elements get the same translate3d values:
transform: translate3d(0px, 0px, 0px);

Any idea what's wrong and how to fix it? is it a bug in the code or did i mis-use the bar chart somehow?

thanks.

**Comment by rainitesh** [comment]
any luck on this one?

**Comment by tannerlinsley** [comment]
This should be fixed in the latest version. Please reopen if problems persist.
