### ISSUE TITLE
Pie/Donut Chart is not working

### ISSUE THREAD

**Issue by ibrahimawadhamid** [tannerlinsley/react-charts#31]
How can you get Pie/Donut to work !

**Comment by tannerlinsley** [comment]
Pie/Donut has been removed from this library for now. Expect it to return soon. For now, I recommend reading this: https://www.data-to-viz.com/caveat/pie.html

**Comment by mmahalwy** [comment]
@tannerlinsley thanks for sharing that link! My wife is a consultant at a top firm and was just telling me their untold rule is not to use pie charts. That link explains it very well!

**Comment by tannerlinsley** [comment]
Nice! That’s awesome 😎
