### ISSUE TITLE
Please allow custom styles for ticks.

### ISSUE THREAD

**Issue by gdebojyoti** [tannerlinsley/react-charts#32]
Currently the way to style the ticks (by CSS) is as follows -

`.Axis:first-child text {` 
    `fill: gray !important;`
    `transform: translate3d(0px, 9px, 0px) !important;` 
`}`

`first-child` = primary/ horizontal axis
`text` = text element (svg)
`!important` overrides the default behaviour of 50deg rotation

**Comment by JLartigaud** [comment]
Hi there, +1

I've been using react-charts but, sadly, it's not possible to customize axis/ticks.

I wanted to reduce a bit the density of ticks displayed when too much data (example : days on a range of 3 months). My solution was, too, using css (by hiding the even or odds). 

@tannerlinsley, are you planning to update this soon ? What are plans for react-charts? Are you openned to submissions?
Anyway, I really appreciate your react projects, cheers!

**Comment by tannerlinsley** [comment]
Very soon, it's likely that axes and ticks get promoted to an HTML layer (similar to cursors). This will allow you to use HTML in your ticks and likewise any custom react component you want. Right now, you can only do textual customization via `format: tickValue => text`. So stay tuned :)
