### ISSUE TITLE
Set custom min max axis values

### ISSUE THREAD

**Issue by rainitesh** [tannerlinsley/react-charts#33]
This chart.js code is not working here

```
ticks: {
                beginAtZero: true,
                min: 0,
                max: 100,
              }
```

**Comment by tannerlinsley** [comment]
You could start by investigating here: https://github.com/react-tools/react-charts/blob/master/src/utils/buildAxis.linear.js#L29

or here: https://github.com/react-tools/react-charts/blob/master/src/components/AxisLinear.js#L43

**Comment by tannerlinsley** [comment]
Also, please comment with a codesandbox.io demonstrating the problem. If we can't replicate it, then we can't fix it properly.

**Comment by rainitesh** [comment]
@tannerlinsley i think I got what I was looking for. Thanks :)

**Comment by pmontu** [comment]
how to provide min value as 0 to axis? 

I am not able to get output on codesandbox.io but the code is at https://codesandbox.io/s/bar-chat-min-axis-not-working-example-t0qy5?file=/src/App.js

![Screenshot 2020-04-09 at 11 53 56 AM](https://user-images.githubusercontent.com/1643802/78864225-d3f54a00-7a58-11ea-8a6f-c20b4a00c7c1.png)

Thank You

**Comment by Zandor300** [comment]
For future self:

To make the bar chart start at zero:

```js
const secondaryAxes = React.useMemo(() => [
    {
        getValue: datum => datum.value,
        elementType: 'bar',
        min: 0 // <--- Do this
    },
], []);
```
