### ISSUE TITLE
Prefix to axis options

### ISSUE THREAD

**Issue by Avery246813579** [tannerlinsley/react-charts#35]
It would be helpful to have an option that we could add a prefix or suffix to an axis. 

For example if you want your Y axis to be dollars, you can add a `$` prefix and on the Y axis and inside the tooltip the prefix will show before the value.

**Comment by tannerlinsley** [comment]
You should be able to use the `axis.format` function. It gives you the value, and you can return whatever display format string you want for it. Give it a shot!

**Comment by Avery246813579** [comment]
> You should be able to use the `axis.format` function. It gives you the value, and you can return whatever display format string you want for it. Give it a shot!

Where are you saying to use that function? Can you give a code example please.

I can customize the tooltip easily but it's adding the prefix to the axis which is the hard part.

**Comment by tannerlinsley** [comment]
```js

const axes = [{
  primary: true,
  type: 'ordinal',
  format: tick => `My Prefix ${tick}`
}, 
{
  type: 'linear'
}]

<Chart axes={axes} />
```
