### ISSUE TITLE
Support for Pie charts

### ISSUE THREAD

**Issue by arronhunt** [tannerlinsley/react-charts#43]
Surprised there's no Pie charts available in this lib!

**Comment by tannerlinsley** [comment]
Me too. 😉

**Comment by tannerlinsley** [comment]
I'll probably add them eventually. On a more personal opinion... I really do not like pie charts. Their use-cases continue to dwindle for me where another chart wouldn't be better.

**Comment by andrewmclagan** [comment]
What are you usually replacing pie charts with?

**Comment by tannerlinsley** [comment]
Bar or column charts almost always.

**Comment by evenstephenr** [comment]
@tannerlinsley if `react-charts` doesn't support pie charts, it would be a very opinionated stance to take.

Unfortunately, it could impact the reach and popularity of the library, depending on the requirements potential users are facing at work 🙁

**Comment by aericson** [comment]
Is anyone working on this? I might take a stab at it.

**Comment by tannerlinsley** [comment]
@aericson, I'm refactoring quite a few things to make it so chart types are code-splittable (via import and register). That said, go for it. I would love to see what you come up with :)

**Comment by aericson** [comment]
> @aericson, I'm refactoring quite a few things to make it so chart types are code-splittable (via import and register). That said, go for it. I would love to see what you come up with :)

Cool, I'll see if I get anywhere with it 😁

**Comment by laurenz-glueck** [comment]
@aericson @tannerlinsley Is there any update on this?
I'm considering to use this package but pie charts are unfortunately essential for our project...

**Comment by aericson** [comment]
@laurenz-glueck nothing from me yet. I'm not sure when I'll be able to put the time on this. I'm definitely interested in participating in it. If anyone wants to kick start it go ahead and I'll follow when life allows.

**Comment by tannerlinsley** [comment]
Pie Charts are simply not on the roadmap of this project. Feel free to use d3 directly for this?

**Comment by barrychapman** [comment]
> @aericson @tannerlinsley Is there any update on this? I'm considering to use this package but pie charts are unfortunately essential for our project...

same

**Comment by tannerlinsley** [comment]
I will not be providing pie chart support any time soon.

**Comment by zaynekomichi** [comment]
Any update on this

**Comment by juan871003** [comment]
This may help those looking for other libraries that support Pie Charts.

https://awesome.cube.dev/?tools=charts
