### ISSUE TITLE
Need finer grained control for formatting tooltip values for multi-axis charts

### ISSUE THREAD

**Issue by erikras** [tannerlinsley/react-charts#45]
[Twitter Thread](https://twitter.com/erikras/status/1195399566868262912) where we discussed it, including [the agreed upon solution](https://twitter.com/tannerlinsley/status/1195407420559749120).

### Exquisite artist's rendition of the required result

![EJbpkS5X0AQxtUW](https://user-images.githubusercontent.com/4396759/68967210-fd7ab400-07df-11ea-9d5b-c824984b5e1c.jpeg)

**Comment by tannerlinsley** [comment]
Of course I can’t get the www site to build now... 🤦‍♂️ next.js

Tanner Linsley

**Comment by tannerlinsley** [comment]
https://react-charts.js.org/examples/multiple-axes

`axis.formatTick` has been renamed to just `axis.format`. Tooltip values will now default to formatting with their respective secondary axis

**Comment by tannerlinsley** [comment]
Available in 2.0.0-beta.6
