### ISSUE TITLE
Bubble chart: Unable to set specific color for each data 

### ISSUE THREAD

**Issue by leelaprasad48** [tannerlinsley/react-charts#52]
Hi Team,

Bubble chart currently takes a prop ```getSeriesStyle={getSeriesStyle}``` which allows to set a color for all the data.
But there is no way through which I can specify what color I need for each data. How do one override the default series color?

**Comment by tannerlinsley** [comment]
Did you try the getDatumStyle prop?

Tanner Linsley

**Comment by evenstephenr** [comment]
@leelaprasad48 closing this ticket, feel free to comment if this should be opened back up

**Comment by SkyFire2013** [comment]
> Did you try the getDatumStyle prop? Tanner Linsley
> […](#)
> On Dec 11, 2019, 2:23 AM -0700, leelaprasad48 ***@***.***>, wrote: Hi Team, Bubble chart currently takes a prop getSeriesStyle={getSeriesStyle} which allows to set a color for all the data. But there is no way through which I can specify what color I need for each data. How do one override the default series color? — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

Is there a detailed documentation on this getDatumStyle?

**Comment by RahmanMonjur** [comment]
const getDatumStyle = React.useCallback(
        datum => ({
          r: 5,
          color: datum.seriesIndex < 2 ? console.log(datum) : 'black'
        }),
        []
      )

and in the Char component add getDatumStyle={getDatumStyle} as props
