### ISSUE TITLE
[Safari] react-charts custom-tooltip example: mouse movement causes graph to disappear, replaced by error message

### ISSUE THREAD

**Issue by prycejs** [tannerlinsley/react-charts#59]
When viewing the 'custom tooltip' example at [the official examples page](https://react-charts.js.org/examples/custom-tooltip) in Safari version 12.1.1 (14607.2.6.1.1) / macOS v10.14.5 (18F132),

the chart displays normally on initial open, and when moving the mouse over part of the graph, the first tooltip appears as normal. Moving the mouse around different areas of the example graph with moderately swift speed or perhaps with a shaking movement results in the graph disappearing and being replaced with an error message reading `An unexpected error has occurred.`

Numerous errors (possibly related) are reported in the developer javascript console, eg:

`
[Error] Error: Invalid value for <rect> attribute y="NaN"
	we (commons.7cad20dceb80bc668535.js:1:238177)
	kl (commons.7cad20dceb80bc668535.js:1:311423)
	(anonymous function) (commons.7cad20dceb80bc668535.js:1:329805)
	(anonymous function)
	unstable_runWithPriority (commons.7cad20dceb80bc668535.js:1:3560)
	Nu (commons.7cad20dceb80bc668535.js:1:327744)
	vu (commons.7cad20dceb80bc668535.js:1:318028)
	vu
	(anonymous function) (commons.7cad20dceb80bc668535.js:1:275823)
	unstable_runWithPriority (commons.7cad20dceb80bc668535.js:1:3560)
	Gi (commons.7cad20dceb80bc668535.js:1:275770)
	Ki (commons.7cad20dceb80bc668535.js:1:275705)
	ue (commons.7cad20dceb80bc668535.js:1:345233)
	Cn (commons.7cad20dceb80bc668535.js:1:259645)
	On (commons.7cad20dceb80bc668535.js:1:260602)
	Mn (commons.7cad20dceb80bc668535.js:1:259890)
	Mn
	unstable_runWithPriority (commons.7cad20dceb80bc668535.js:1:3560)
	(anonymous function) (commons.7cad20dceb80bc668535.js:1:259260)
	(anonymous function)
[Error] Error: Invalid value for <rect> attribute height="NaN"
	we (commons.7cad20dceb80bc668535.js:1:238177)
	kl (commons.7cad20dceb80bc668535.js:1:311423)
	(anonymous function) (commons.7cad20dceb80bc668535.js:1:329805)
	(anonymous function)
	unstable_runWithPriority (commons.7cad20dceb80bc668535.js:1:3560)
	Nu (commons.7cad20dceb80bc668535.js:1:327744)
	vu (commons.7cad20dceb80bc668535.js:1:318028)
	vu
	(anonymous function) (commons.7cad20dceb80bc668535.js:1:275823)
	unstable_runWithPriority (commons.7cad20dceb80bc668535.js:1:3560)
	Gi (commons.7cad20dceb80bc668535.js:1:275770)
	Ki (commons.7cad20dceb80bc668535.js:1:275705)
	ue (commons.7cad20dceb80bc668535.js:1:345233)
	Cn (commons.7cad20dceb80bc668535.js:1:259645)
	On (commons.7cad20dceb80bc668535.js:1:260602)
	Mn (commons.7cad20dceb80bc668535.js:1:259890)
	Mn
	unstable_runWithPriority (commons.7cad20dceb80bc668535.js:1:3560)
	(anonymous function) (commons.7cad20dceb80bc668535.js:1:259260)
	(anonymous function)
[Error] Error: Invalid value for <rect> attribute y="NaN"
	we (commons.7cad20dceb80bc668535.js:1:238177)
	kl (commons.7cad20dceb80bc668535.js:1:311423)
	(anonymous function) (commons.7cad20dceb80bc668535.js:1:329805)
	(anonymous function)
	unstable_runWithPriority (commons.7cad20dceb80bc668535.js:1:3560)
	Nu (commons.7cad20dceb80bc668535.js:1:327744)
	vu (commons.7cad20dceb80bc668535.js:1:318028)
	vu
	(anonymous function) (commons.7cad20dceb80bc668535.js:1:275823)
	unstable_runWithPriority (commons.7cad20dceb80bc668535.js:1:3560)
	Gi (commons.7cad20dceb80bc668535.js:1:275770)
	Ki (commons.7cad20dceb80bc668535.js:1:275705)
	hu (commons.7cad20dceb80bc668535.js:1:314596)
	Oa (commons.7cad20dceb80bc668535.js:1:293213)
	Oa
	(anonymous function) (commons.7cad20dceb80bc668535.js:1:161385)
[Error] Error: Invalid value for <rect> attribute height="NaN"
	we (commons.7cad20dceb80bc668535.js:1:238177)
	kl (commons.7cad20dceb80bc668535.js:1:311423)
	(anonymous function) (commons.7cad20dceb80bc668535.js:1:329805)
	(anonymous function)
	unstable_runWithPriority (commons.7cad20dceb80bc668535.js:1:3560)
	Nu (commons.7cad20dceb80bc668535.js:1:327744)
	vu (commons.7cad20dceb80bc668535.js:1:318028)
	vu
	(anonymous function) (commons.7cad20dceb80bc668535.js:1:275823)
	unstable_runWithPriority (commons.7cad20dceb80bc668535.js:1:3560)
	Gi (commons.7cad20dceb80bc668535.js:1:275770)
	Ki (commons.7cad20dceb80bc668535.js:1:275705)
	hu (commons.7cad20dceb80bc668535.js:1:314596)
	Oa (commons.7cad20dceb80bc668535.js:1:293213)
	Oa
	(anonymous function) (commons.7cad20dceb80bc668535.js:1:161385)
`

etc

To discover and replicate this issue I was using the Safari Browser: 
 Safari version 12.1.1 (14607.2.6.1.1) / macOS v10.14.5 (18F132),
and I attempted to replicate this problem in Chrome but was unable to cause the issue to occur. My Chrome build was Chrome 80.0.3987.132 (Official Build) (64-bit)

**Comment by tannerlinsley** [comment]
Due to a massive overhaul and rewrite of React Charts to TypeScript and a massively upgraded public API, this issue is being bulk closed for triage. The latest version can be tested via the `react-charts@beta` tag. Documentation is in the process of being upgraded, but thankfully, everything is fully typed now, so you can explore the API that way for now.

If, *after testing or playing with the v3 beta*, you believe your issue is still not addressed or relevant, feel free to open a new issue.
