### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by angelsalazar** [tannerlinsley/react-charts#65]
Where can I find detail documentation about the react-charts components' API?

**Comment by diffractometer** [comment]
@tannerlinsley I think my question would best be under the documentation thread as well here, as this is what I did.

When I copy/paste from the line example on the homepage into an empty CRA I get

```
./src/App.js
Module not found: Can't resolve 'components/Box' in '/Users/hunterhusar/Code/covid-live/covid-live/src'
```

I'm just wondering where can I find in the docs something about `components/Box`...

Thanks for your time! I'm a huge fan of your Table component, didn't even see you did a chart till today, stoked!

**Comment by evenstephenr** [comment]
@angelsalazar the react-charts API and some examples have been published here

https://react-charts.tanstack.com/docs/api
