### ISSUE TITLE
Chart expands with parent but won't shrink back with parent

### ISSUE THREAD

**Issue by cbdeveloper** [tannerlinsley/react-charts#70]
The following chart is expanding with the parent, but is not shrinking with the parent.

`LS.Container_DIV` is set to `width: 100%;`

And the parent of `LS.Container_DIV` is a FlexItem with `flex: 1 1 900%`.

There are other components inside of that FlexItem and they expand and shrink accordingly without any issues without the Chart.

But when I add the Chart, it initially loads with the correct `width: 100%;` (perfect width without scroll bars for any initial width) and it is able to expand (resizing the screen) without any issues. But if I try to shrink it back (resizing back the screen), it does not work. The chart remains with the larger width and I get a horizontal scroll.

Am I doing something wrong or is this a bug?

```
import React from 'react';
import styled from 'styled-components';
import { useSelector } from 'react-redux';
import { Chart } from "react-charts";

const LS = {};

LS.Container_DIV = styled.div`
  width: 100%;
  height: 300px;
  font-family: Arial, Helvetica, sans-serif;
`;

const dataDoc = [
  [new Date(Date.UTC(2020, 2, 26)), 1505.1],
  [new Date(Date.UTC(2020, 2, 29)), 1252.1],
  [new Date(Date.UTC(2020, 2, 30)), 1324.1],
  [new Date(Date.UTC(2020, 2, 31)), 1455.1],
  [new Date(Date.UTC(2020, 3, 1)), 1448.1]
];

function CurrencyChart(props) {
  console.log('Rendering CurrencyChart...');
 
  const data = React.useMemo(
    () => [
      {
        label: "Series 10",
        data: dataDoc
      }
    ],
    []
  );

  const axes = React.useMemo(
    () => [
      { primary: true, type: "utc", position: "bottom" },
      // { type: "linear", position: "left" }
      {
        type: "linear",
        position: "left",
        format: value => "$" + parseFloat(value.replace(/,/g, "")).toFixed(2)
      }
    ],
    []
  );

  return (
    <LS.Container_DIV>
      <Chart data={data} axes={axes} tooltip />
    </LS.Container_DIV>
  );
}

export default CurrencyChart;
```

**Comment by tannerlinsley** [comment]
Due to a massive overhaul and rewrite of React Charts to TypeScript and a massively upgraded public API, this issue is being bulk closed for triage. The latest version can be tested via the `react-charts@beta` tag. Documentation is in the process of being upgraded, but thankfully, everything is fully typed now, so you can explore the API that way for now.

If, *after testing or playing with the v3 beta*, you believe your issue is still not addressed or relevant, feel free to open a new issue.
