### ISSUE TITLE
Tooltip for 'time' primary axis not showing time correctly

### ISSUE THREAD

**Issue by GreenAsJade** [tannerlinsley/react-charts#76]
A random number less than 1 is appearing where a date should appear.

<img width="1108" alt="Screen Shot 2020-04-13 at 3 01 49 pm (2)" src="https://user-images.githubusercontent.com/61894/79095730-54d67d80-7d9a-11ea-9e9f-204084e20b4d.png">

```
function StatsChart(props: JosekiStatsModalProperties) {
    const stats_data = React.useMemo(() => (
        [
            {
                label: 'Total Page Visits',
                data: props.daily_page_visits.map(day => ({x: new Date(day.date), y: day.pageVisits}))
            },
            {
                label: 'Explore Page Visits',
                data: props.daily_page_visits.map(day => [new Date(day.date), day.explorePageVisits])
            },
            {
                label: 'Play Mode Visits',
                data: props.daily_page_visits.map(day => [new Date(day.date), day.playPageVisits])
            },
            {
                label: 'Guest Visits',
                data: props.daily_page_visits.map(day => [new Date(day.date), day.guestPageVisits])
            }
        ]), [props]);

    const axes =
        [
            { primary: true, type: 'time', position: 'bottom' },
            { type: 'linear', position: 'left' }
        ];

    const series = {
          showPoints: false
        };

    return (
        <Chart
            data={stats_data} axes={axes} series={series} tooltip
        />
    );
}

export class JosekiStatsModal extends Modal<Events, JosekiStatsModalProperties, any> {

    render() {
        //console.log(this.props.daily_page_visits);
        return (
            <div className="Modal JosekiStatsModal" ref="modal">
                <div className="header">{_("Joseki Explorer Stats - Daily Position Loads")}</div>
                <div className="daily-visit-results">
                    <StatsChart daily_page_visits={this.props.daily_page_visits}/>
                </div>
            </div>
        );
    }
}

```

**Comment by tannerlinsley** [comment]
You must round off your dates to the time unit you want to display. Eg. if you want hourly, you must ensure that your dates do not have arbitrary minutes, seconds and microseconds. I would suggest utilizing a date rounding library or d3's time utilities to make this a bit easier.

**Comment by GreenAsJade** [comment]
Having looked at this, I'm not sure what is driving me to select a limited precision for dates here.

I was expecting the tooltip header to render the exact date that was supplied as the X value for those points.

**Comment by GreenAsJade** [comment]
Rounding off hours and all below did deliver the visual result I was looking for, thanks :) 

`data: props.daily_page_visits.map(day => ({x: new Date(day.date).setHours(0, 0, 0, 0), y: day.pageVisits}))`

**Comment by tannerlinsley** [comment]
I know, months was a bad example. Most of this is because of D3’s auto formatting which is based on specificity of time stamps.  Since your time has a non zero specificity of milliseconds, it’s showing you The x value of how many seconds (.92) have elapsed at that point. If you zeroed out the milliseconds, it would likely show a time like 12:45

**Comment by samjbmason** [comment]
Could this be why the the first point is starting further along the x-axis than it should? I have start using the library and have found that my first point doesn t align with the y-axis and starts further in

**Comment by tannerlinsley** [comment]
There is a way to "clamp" the axis bounds actually. But it's obviously undocumented like a majority of this library lol. Let me find the source...

**Comment by tannerlinsley** [comment]
Try setting `min` or `hardMin` and `max` or `hardMax` options on the axis to the values of your start/end range. I believe that will clamp the axis.

**Comment by samjbmason** [comment]
I checked the source code and it looks like it needs to be a number but Im using the time scale?

**Comment by samjbmason** [comment]
Ignore me I got it working by converting the date object to a number and it worked
