### ISSUE TITLE
Support for custom axis names for Column Graph?

### ISSUE THREAD

**Issue by devhid** [tannerlinsley/react-charts#78]
I apologize in advance if this is already supported.

I'm looking at the documentation and the Column Chart seems like what I need for my project, but it seems like there's no way to edit the names of the groups. They are preset to be named "Ordinal Group {number}" which is not really idea since my data is categorical with numeric values.

**Comment by evenstephenr** [comment]
@devhid did @RobertMcReed 's answer fix this for you?

**Comment by devhid** [comment]
> @devhid did @RobertMcReed 's answer fix this for you?

Yes, it did. Thank you.
