### ISSUE TITLE
Facilitate styling the top line of area charts

### ISSUE THREAD

**Issue by franky47** [tannerlinsley/react-charts#79]
I was looking at recreating this design with react-charts:

<img width="598" alt="chiffre-charts" src="https://user-images.githubusercontent.com/1174092/80569200-b6345880-89f8-11ea-84bf-a6089d4effdb.png">

It contains two visual components:
- A line with no points, with a blue stroke of 2px
- A gradient area under the curve

After a discussion with @tannerlinsley [on Twitter](https://twitter.com/fortysevenfx/status/1255230417604677633), who pointed out that Area graphs are made of two components (a line and a filled path, perfect !), I looked into styling them separately using `getSeriesStyle`.

Looking at the Area component code, both the [line](https://github.com/tannerlinsley/react-charts/blob/63e6ae6471aad9e6a864d1f3704702c04f954d64/src/seriesTypes/Area.js#L70-L75) and the [area path](https://github.com/tannerlinsley/react-charts/blob/63e6ae6471aad9e6a864d1f3704702c04f954d64/src/seriesTypes/Area.js#L57-L61) use the same styling inputs, with the exception of the line having an extra `fill: none` property.

Unfortunately for this design, setting a stroke of 2px for the line would also set it for the area, which produces an undesired outline at the bottom and sides of the graph:

<img width="805" alt="Screenshot 2020-04-29 at 09 19 09" src="https://user-images.githubusercontent.com/1174092/80570104-825a3280-89fa-11ea-9048-4122002aaf76.png">

One way I solved this in my project was to use external CSS to disable the stroke on the area path:

```css
g.Series > g > path:first-child {
  /* Rendered path uses inline styles, so !important must be used to override them: */
  stroke-width: 0 !important;
}
```

I would like to open a PR suggesting an additional `area` property in what is returned by `getSeriesStyle`, so that each path can be styled separately without relying on external CSS.

Example:

```ts
const getSeriesStyle = React.useCallback(
  () => ({
    area: {
      // See the "Custom Styles" example for gradients usage
      fill: `url(#graph-gradient)`
    },
    line: {
      strokeWidth: '2px',
      stroke: 'blue'
    }
  }),
  []
)
```

In order not to break existing designs, the area path could use properties from both line and area:
```diff
const areaPathProps = {
    d: areaPath,
    style: {
      ...defaultAreaStyle,
      ...style,
      ...style.line,
+     ...style.area
    }
  };
```

Comments and suggestions are welcome !

**Comment by tannerlinsley** [comment]
Yep a PR for this would be great!

**Comment by fralfarom** [comment]
Hello!! is this available? If so, how can I use it?
