### ISSUE TITLE
How to use 'getSeriesStyle' or any other props to edit the line chart?

### ISSUE THREAD

**Issue by twilighthook** [tannerlinsley/react-charts#84]
![1588931080153](https://user-images.githubusercontent.com/31069535/81394137-1000f500-9154-11ea-88e0-655bc3c86918.jpg)
![1588931203868](https://user-images.githubusercontent.com/31069535/81394141-11322200-9154-11ea-9b9a-84f16708d4ae.jpg)

Is there any generate the series like above? (Bottom is right now version)
Which getStyle function should I use? 
Thanks !

**Comment by SkyFire2013** [comment]
This works for me
<pre>
const data = React.useMemo(
    () => [
      {
        label: 'Series 1',
        data: [
          { primary: 'Oct', secondary: 10 },
        ],
        color: '#1f77b4'
      },
      {
        label: 'Series 2',
        data: [
          { primary: 'Oct', secondary: 5 },
        ],
        color: '#ff7f0e'
      },
      {
        label: 'Series 3',
        data: [
          { primary: 'Oct', secondary: 7 },
        ],
        color: '#ffff4d'
      }
    ],
    []
  )
</pre>
