### ISSUE TITLE
How 'Area' type chart has points at reverse point?

### ISSUE THREAD

**Issue by twilighthook** [tannerlinsley/react-charts#85]
Line chart has 'showPoints' prop can show.
How Area chart show the points without modify the source code.
Or maybe the only way is add showPoints prop and return Point component in Area component?

**Comment by evenstephenr** [comment]
@twilighthook you should be able to use the `showPoints` control on an Area series as well as a line series, example below

```
...

  const series = React.useMemo(
    () => ({
      type: "area",
      showPoints: true,
    }),
    []
  );

...
```

Does this solve the issue for you?
