### ISSUE TITLE
Pass raw values as well as or instead of formatted value

### ISSUE THREAD

**Issue by samjbmason** [tannerlinsley/react-charts#88]
I was wondering if it would be possible topass the raw arguments or at least the raw value for the userFormat so that the user can calculate there own format based on the raw value rather than the stringified one.

https://github.com/tannerlinsley/react-charts/blob/e99e9686b20c42965c007dd63f85e68d3953f259/src/utils/buildAxis.linear.js#L263

**Comment by evenstephenr** [comment]
@samjbmason you should be able to use the `format` param on an axis config to customize the expression of the ticks on your axis

https://github.com/tannerlinsley/react-charts/blob/e99e9686b20c42965c007dd63f85e68d3953f259/src/utils/buildAxis.linear.js#L51

Does this resolve the issue for you?

**Comment by samjbmason** [comment]
I actually ended up using another library in the end
