### ISSUE TITLE
Nextjs

### ISSUE THREAD

**Issue by jonasgroendahl** [tannerlinsley/react-charts#90]
Hey,

I'm trying to use this library in a nextjs project. If I'm on the page where chart is, i get this error:

```
Server Error
ReferenceError: regeneratorRuntime is not defined
```

I know this is a SSR issue but I'm new to nextjs so I'm not sure how to fix it. Any ideas?

**Comment by haderman** [comment]
Hi! @jonasgroendahl I have the same problem, did you fix it?

**Comment by haderman** [comment]
I fixed this importing the module like this

`const Chart = dynamic(() =>
  import("react-charts").then(mod => mod.Chart),
  { ssr: false }
)`

https://nextjs.org/docs/advanced-features/dynamic-import
